### PR TITLE
Relying entirely on qbshared.vehicles table

### PR DESCRIPTION
**Pull request by r0adra93**
**Describe Pull request**

Removed the need to list categories in the vehcileshop/config.lua

it was duplicate work listing the category in the variable and the store in the variable and then listing the category into the vehiclestore/config.lua for each store created.

Since the table holds both the stores and the category there is no need to list the category in the config file.

So, now the client.lua generates the categories from the qbshared.vehicles table.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by KamuiKody** [comment]
have tested this in my server works just fine. Looks pretty well written too! Good job simplifying the config!

**Comment by r0adra93** [comment]
> have tested this in my server works just fine. Looks pretty well written too! Good job simplifying the config!

Kody, before they approve this for merge you need to find the link that states, "review" and you need to select approve.

**Review by KamuiKody — APPROVED** [review]
have tested this in my server works just fine. Looks pretty well written too! Good job simplifying the config!

**Review by jeann2013 — APPROVED** [review]

**Comment by jeann2013** [comment]
I tested this improvement

**Pull request closed without merging**
