### PR TITLE
feat(ManagedShops): Player ID instead of Closest Player

### PR DESCRIPTION
**Pull request by uShifty**
This pull request replaces the closest player to a selected player id. This was tested but not on a production build just made sure it worked didnt really go too in depth.

### CODE REVIEW

**Comment by xenfovn** [comment]
you are selling to someone who is not there, this is not roleplay

**Comment by ARSSANTO** [comment]
@xenfovn um this patch is for some glitch prevent

**Comment by uShifty** [comment]
> you are selling to someone who is not there, this is not roleplay

Read the code changes if you are commenting on a pull request. No you cannot sell to someone who is not their. I added a server side distance check with the max of 3 units.

**Review by ARSSANTO — APPROVED** [review]
Working perfect without a single issue

**Pull request merged**
