### PR TITLE
Fixed error when spawning/loading into managed shop

### LINKED ISSUE #89: [BUG] Managed vehicle shop
Hello.
So basically the issue is when you join the server and if are in the zone of the shop when you spawn it gets nil value on the job check 
https://prnt.sc/2422ltl

### PR DESCRIPTION
**Pull request by OlliePugh**
Fixed nil job while qbcore is retrieving player data

Fixes #89 and #81

### CODE REVIEW

**Comment by xenfovn** [comment]
wew ,it's irrelevant, a useless pr

**Comment by OlliePugh** [comment]
But fixes something that lots of GitHub issues are made about? Doesn't seem completely useless

**Comment by xenfovn** [comment]
you shouldn't do this, the only thing they need to do when they get this error is go out of the store and go in again, they have loaded the vehicles while in the polyzone

**Comment by OlliePugh** [comment]
I understand. This PR does not affect the business logic, but suppresses an error message. Don’t see what the huge issue is? Just a refactor/polish change

**Pull request closed without merging**
