### PR TITLE
Solves incorrect time deduction from financing

### PR DESCRIPTION
**Pull request by Re1ease**
**Describe Pull request**
As the title states. 
Replaces GetGameTime() with os.time(). 
Tested by myself with success and by the person who created the issue.

If your PR is to fix an issue, mention that issue here
#247 

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

### CODE REVIEW

**Comment by Z3rio** [comment]
Looks good to me. Just unsure if it will be merged since it seems like they wanted to use ingame time with the default script and your PR seems to change it to irl time.

But overall I dont see any issue in it, just unsure if it will be merged.

**Review by Z3rio — APPROVED** [review]
Looks good to me. Just unsure if it will be merged since it seems like they wanted to use ingame time with the default script and your PR seems to change it to irl time.

But overall I dont see any issue in it, just unsure if it will be merged.

**Comment by GhzGarage** [comment]
Yeah the purpose of this was so that a player had to actually be playing for the timer to go down. It works fine but there’s some obvious math issues happening. Can be solved by upping the config time considerably

**Comment by Re1ease** [comment]
This PR reflects the playtime of the player. It logs the os.time() that the player "loggedIn" and then compares the os.time() when the player "logsOut". It then calculates the amount of time that has passed between those values to reduce the finance time correctly. 

If the player has been logged into their character for 5 minutes, it would then remove 5 minutes of the finance time.
The issue before was that the timer wouldn't correctly calculate the amount of time that the player was logged into their character. This PR seems to fix that.

**Comment by Re1ease** [comment]
> Looks good to me. Just unsure if it will be merged since it seems like they wanted to use ingame time with the default script and your PR seems to change it to irl time.
> 
> But overall I dont see any issue in it, just unsure if it will be merged.

Oh, I do understand what you mean now. Fair enough.

**Pull request closed without merging**
