### PR TITLE
Added support for shops outside of the two default ones

### PR DESCRIPTION
**Pull request by OlliePugh**
First time using LUA, Be gentle😆

### CODE REVIEW

**Comment by OlliePugh** [comment]
Fixes #72

**Comment by OlliePugh** [comment]
> 

Yup working perfectly for me :)

**Comment by xenfovn** [comment]
image
sometime it not work

**Comment by OlliePugh** [comment]
> image sometime it not work

Can you send me the part for your shop in the config please.

**Comment by xenfovn** [comment]
image
image
image
my debug

**Comment by OlliePugh** [comment]
Can you print out what `Config.Shops[ClosestShop]['Job'] is?

Also make sure you left the zone and re entered after restarting the plugin, as it will automatically assume you are not in a zone, then wait for you to enter one.

**Comment by xenfovn** [comment]
image
i find it lol

**Comment by OlliePugh** [comment]
Do you wanna take this to discord chat instead of polluting the issue thread?  Puggy#7595

**Comment by OlliePugh** [comment]
Previous comments were just due to a bad restart location, funky stuff happens when you restart the plugin inside of a garage.

**Comment by AleixCat** [comment]
First of all, great job! 
I had an issue with the user managed shops, because it doesn't detect the player job at all, I found a solution by replacing the line in **client.lua:288** with this: `while insideZones[name] and PlayerData.job.name == Config.Shops[name]['Job'] do`

**Comment by OlliePugh** [comment]
> First of all, great job! I had an issue with the user managed shops, because it doesn't detect the player job at all, I found a solution by replacing the line in **client.lua:288** with this: `while insideZones[name] and PlayerData.job.name == Config.Shops[name]['Job'] do`

Of course, I didn't spot that, thank you, I will amend that now. 

I couldn't really test the managed shops due to not having any friends to test it with ;) 😆

**Comment by izMystic** [comment]
works for me, have yet to add another shop tho

**Comment by HavocHN** [comment]
#87

**Comment by xenfovn** [comment]
> #87

this issue is not related , it is valid

**Pull request merged**
