### PR TITLE
Fixed resource thinking user is in wrong shop

### LINKED ISSUE #88: Swipe through PDM cars and go to luxury to get access to the luxury menu
PDM Job = none
Luxury Job = cardealer

situation: after swiping through the cars in PDM, to go Luxury shop. Now you have full access to Luxury menu and can even buy the cars.

### PR DESCRIPTION
**Pull request by OlliePugh**
- Refered to global state for inside shop instead of local

Fixes #88 #87 #92 

The `ClosestShop` variable was redundant as its value could be derived from `InsideZones` therefore I have removed it as it was adding complexity to the global space of the resouce, and was causing some issue mainting its value.

The issue was that the value of ClosestShop was used at the local level inside of the functions, instead of reffering back to the global state. Therefore I have removed the ClosestShop value and instead have created a method to retrieve the ClosestShop to replace the variable ClosestShop.

This seems to of removed the issue with the script thinking users are still in PMD or Luxury when they are not.

### CODE REVIEW

**Comment by zeemkarry** [comment]
Its working for me!
Thanks for the fix. I can now even add more shops without any conflict.

**Comment by xenfovn** [comment]
it work but need testing realtime , Can you create multiple finance positions?

**Comment by zeemkarry** [comment]
I actually don't need multiple finance location. so one location is fine for me

**Comment by xenfovn** [comment]
if so you can only pay cardealer , if there are many shops with different job , they cant use this feature

**Comment by OlliePugh** [comment]
Still not sure I 100% understand what the problem is, can you please give a step by step example of an issue tou are facing

**Review by xenfovn — APPROVED** [review]
TESTED 2 day , no problem

**Comment by krishnz12** [comment]
Sir can you add job authentication in pdm because every one is accessing the pdm and buying the vehicle can you block the access of buy and swap vehicles when pdm sales person enable the buy option to costumers

**Comment by OlliePugh** [comment]
> Sir can you add job authentication in pdm because every one is accessing the pdm and buying the vehicle can you block the access of buy and swap vehicles when pdm sales person enable the buy option to costumers     
> 
> 

Read the 'config.lua' it explains how managed vs free use shops work.

A pull request isn't the right place to request new features or help as well.

**Pull request merged**
