### PR TITLE
Fix Commission.

### PR DESCRIPTION
**Pull request by Holidayy95**
Most of the Player.Functions were uncapitalised.

player.Functions -> Player.Functions

### CODE REVIEW

**Comment by NotReloads** [comment]
its defined as lowercase, so leave it.

**Comment by Holidayy95** [comment]
It doesn't work if they are lower case P's. So not sure what you mean, I only got commission when I edited it.

**Comment by Brusein** [comment]
I tested this today and when I capitalized Players it did not work, when I used lower case it did, I'm on the latest code in the repo. Just letting you know I tested, if it works for you that's great. 

Thank you!

**Comment by BerkieBb** [comment]
> It doesn't work if they are lower case P's. So not sure what you mean, I only got commission when I edited it.

That's not the case at all, it's the variable that defines what it is, in this case it's lower so that's what it stays to work

**Pull request closed without merging**
